name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - '**.nacl'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Salto CLI
        uses: actions/checkout@v3
        with:
          repository: salto-io/tmp-saas-cli-bin-repo
          token: ${{ secrets.GH_TOKEN }}
          path: salto-saas-cli
        
      - name: Run Deploy
        run: |
          cd salto-saas-cli
          tar xf linux-x64.tar
          ./saas-cli deploy --git-repo workingman/gwr-cicd --branch-name master -p github --commit-message "statefile update post deploy to d3v-salto" --env-id 605f5024-6ccc-4fbe-868f-e58e5f9b28b1 --accounts zendesk
        env: 
          API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}